name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Rust Caching
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
